// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.4
// source: protos/intf.proto

// protoc requirements
//  protoc >3.12.0
//  protoc-gen-go >1.23.0
//  protoc-gen-go-grpc >1.27.0

package rpcintf

import (
	proto "github.com/golang/protobuf/proto"
	any1 "github.com/golang/protobuf/ptypes/any"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MsgAgent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string    `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Body *any1.Any `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *MsgAgent) Reset() {
	*x = MsgAgent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_intf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAgent) ProtoMessage() {}

func (x *MsgAgent) ProtoReflect() protoreflect.Message {
	mi := &file_protos_intf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAgent.ProtoReflect.Descriptor instead.
func (*MsgAgent) Descriptor() ([]byte, []int) {
	return file_protos_intf_proto_rawDescGZIP(), []int{0}
}

func (x *MsgAgent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MsgAgent) GetBody() *any1.Any {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_protos_intf_proto protoreflect.FileDescriptor

var file_protos_intf_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x66, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x72, 0x70, 0x63, 0x69, 0x6e, 0x74, 0x66, 0x1a, 0x19, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x49, 0x0a, 0x09, 0x6d, 0x73, 0x67, 0x5f, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x32, 0x47, 0x0a, 0x09, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x12,
	0x3a, 0x0a, 0x0a, 0x54, 0x65, 0x73, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x12, 0x2e,
	0x72, 0x70, 0x63, 0x69, 0x6e, 0x74, 0x66, 0x2e, 0x6d, 0x73, 0x67, 0x5f, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x1a, 0x12, 0x2e, 0x72, 0x70, 0x63, 0x69, 0x6e, 0x74, 0x66, 0x2e, 0x6d, 0x73, 0x67, 0x5f,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0b, 0x5a, 0x09, 0x2e,
	0x2f, 0x72, 0x70, 0x63, 0x69, 0x6e, 0x74, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_intf_proto_rawDescOnce sync.Once
	file_protos_intf_proto_rawDescData = file_protos_intf_proto_rawDesc
)

func file_protos_intf_proto_rawDescGZIP() []byte {
	file_protos_intf_proto_rawDescOnce.Do(func() {
		file_protos_intf_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_intf_proto_rawDescData)
	})
	return file_protos_intf_proto_rawDescData
}

var file_protos_intf_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_intf_proto_goTypes = []interface{}{
	(*MsgAgent)(nil), // 0: rpcintf.msg_agent
	(*any1.Any)(nil), // 1: google.protobuf.Any
}
var file_protos_intf_proto_depIdxs = []int32{
	1, // 0: rpcintf.msg_agent.body:type_name -> google.protobuf.Any
	0, // 1: rpcintf.Streaming.TestStream:input_type -> rpcintf.msg_agent
	0, // 2: rpcintf.Streaming.TestStream:output_type -> rpcintf.msg_agent
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_intf_proto_init() }
func file_protos_intf_proto_init() {
	if File_protos_intf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_intf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgAgent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_intf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_intf_proto_goTypes,
		DependencyIndexes: file_protos_intf_proto_depIdxs,
		MessageInfos:      file_protos_intf_proto_msgTypes,
	}.Build()
	File_protos_intf_proto = out.File
	file_protos_intf_proto_rawDesc = nil
	file_protos_intf_proto_goTypes = nil
	file_protos_intf_proto_depIdxs = nil
}
