// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.4
// source: protos/msgs.proto

// protoc requirements
//  protoc >3.12.0
//  protoc-gen-go >1.23.0
//  protoc-gen-go-grpc >1.27.0

package pbmsg

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Msg_A struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Src  string `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Data string `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Msg_A) Reset() {
	*x = Msg_A{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_msgs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg_A) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg_A) ProtoMessage() {}

func (x *Msg_A) ProtoReflect() protoreflect.Message {
	mi := &file_protos_msgs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg_A.ProtoReflect.Descriptor instead.
func (*Msg_A) Descriptor() ([]byte, []int) {
	return file_protos_msgs_proto_rawDescGZIP(), []int{0}
}

func (x *Msg_A) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *Msg_A) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type Msg_B struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Src  string `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Data int32  `protobuf:"varint,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Msg_B) Reset() {
	*x = Msg_B{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_msgs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg_B) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg_B) ProtoMessage() {}

func (x *Msg_B) ProtoReflect() protoreflect.Message {
	mi := &file_protos_msgs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg_B.ProtoReflect.Descriptor instead.
func (*Msg_B) Descriptor() ([]byte, []int) {
	return file_protos_msgs_proto_rawDescGZIP(), []int{1}
}

func (x *Msg_B) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *Msg_B) GetData() int32 {
	if x != nil {
		return x.Data
	}
	return 0
}

type Msg_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Src string `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	A   string `protobuf:"bytes,2,opt,name=a,proto3" json:"a,omitempty"`
	B   int32  `protobuf:"varint,3,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *Msg_C) Reset() {
	*x = Msg_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_msgs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg_C) ProtoMessage() {}

func (x *Msg_C) ProtoReflect() protoreflect.Message {
	mi := &file_protos_msgs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg_C.ProtoReflect.Descriptor instead.
func (*Msg_C) Descriptor() ([]byte, []int) {
	return file_protos_msgs_proto_rawDescGZIP(), []int{2}
}

func (x *Msg_C) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *Msg_C) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

func (x *Msg_C) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

var File_protos_msgs_proto protoreflect.FileDescriptor

var file_protos_msgs_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x62, 0x6d, 0x73, 0x67, 0x22, 0x2d, 0x0a, 0x05, 0x6d, 0x73,
	0x67, 0x5f, 0x41, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x73, 0x72, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2d, 0x0a, 0x05, 0x6d, 0x73, 0x67,
	0x5f, 0x42, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x73, 0x72, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x35, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x5f,
	0x43, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x73, 0x72, 0x63, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01,
	0x61, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x62, 0x42,
	0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x62, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protos_msgs_proto_rawDescOnce sync.Once
	file_protos_msgs_proto_rawDescData = file_protos_msgs_proto_rawDesc
)

func file_protos_msgs_proto_rawDescGZIP() []byte {
	file_protos_msgs_proto_rawDescOnce.Do(func() {
		file_protos_msgs_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_msgs_proto_rawDescData)
	})
	return file_protos_msgs_proto_rawDescData
}

var file_protos_msgs_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_msgs_proto_goTypes = []interface{}{
	(*Msg_A)(nil), // 0: pbmsg.msg_A
	(*Msg_B)(nil), // 1: pbmsg.msg_B
	(*Msg_C)(nil), // 2: pbmsg.msg_C
}
var file_protos_msgs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_msgs_proto_init() }
func file_protos_msgs_proto_init() {
	if File_protos_msgs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_msgs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg_A); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_msgs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg_B); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_msgs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_msgs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_msgs_proto_goTypes,
		DependencyIndexes: file_protos_msgs_proto_depIdxs,
		MessageInfos:      file_protos_msgs_proto_msgTypes,
	}.Build()
	File_protos_msgs_proto = out.File
	file_protos_msgs_proto_rawDesc = nil
	file_protos_msgs_proto_goTypes = nil
	file_protos_msgs_proto_depIdxs = nil
}
